// Generated by https://quicktype.io

export interface IPokemonsResponse {
  count: number;
  next: string;
  previous: null;
  results: SmallPokemon[];
}

export interface SmallPokemon {
  id: string;
  name: string;
  url: string;
  img: string;
}
